// backends/api-backend.js
// The FAST backend: talks directly to ChatGPT's internal backend-api using the
// logged-in session's cookies + a short-lived access token. Returns true SSE
// token streaming. Much faster than the UI backend, but MORE FRAGILE.
//
// IMPORTANT — why this usually fails on its own (and that's expected):
//   ChatGPT's modern streaming endpoint is /backend-api/f/conversation (the
//   "fortified" route). It requires THREE anti-bot tokens generated by
//   obfuscated client-side JavaScript on each request:
//     - openai-sentinel-proof-token        (a proof-of-work)
//     - openai-sentinel-turnstile-token    (a Cloudflare Turnstile artifact)
//     - openai-sentinel-chat-requirements-token
//   These are generated by OpenAI's own JS precisely to stop scripted callers.
//   We do NOT reverse-engineer or forge them — that would be circumventing
//   access controls on a service we don't own. As a result, a standalone call
//   here is rejected (403/422). In BACKEND=auto mode the server transparently
//   falls back to the playwright backend, which runs the REAL client JS and so
//   legitimately produces these tokens. Keep this backend for the case where
//   you're pointing it at your own OpenAI API key instead (see OPENAI_API_KEY).
//
// Flow (logged-in-web-session path):
//   1. Open a logged-in browser context (cookies from the private session.json).
//   2. GET https://chatgpt.com/api/auth/session  → { accessToken: "..." }
//   3. POST https://chatgpt.com/backend-api/f/conversation with the token +
//      a conversation payload, Accept: text/event-stream.
//   4. Parse SSE lines (data: {...}) → emit content_part deltas.
//   Step 3 will be rejected without the sentinel tokens — this is the
//   expected failure that triggers fallback to the playwright backend.

import { randomUUID } from "node:crypto";
import { withSessionScope } from "../session.js";
import { rateLimitResponseInfo } from "../request-helpers.js";

const BASE = "https://chatgpt.com";

/**
 * Fetch an access token from the session endpoint using the saved cookies.
 * @param {import('playwright').Page} page
 * @returns {Promise<string>} accessToken
 */
async function getAccessToken(page) {
  const resp = await page.request.get(`${BASE}/api/auth/session`);
  if (!resp.ok()) {
    throw new Error(`api-backend: auth/session returned ${resp.status()}`);
  }
  const json = await resp.json();
  const token = json?.accessToken;
  if (!token) {
    throw new Error("api-backend: no accessToken in /api/auth/session response");
  }
  return token;
}

/**
 * Build the conversation request body. This mirrors the default (GPT) web
 * payload as of 2026-07. Keep it minimal so minor field drift is less likely
 * to break it.
 */
function buildPayload(message) {
  return {
    action: "next",
    messages: [
      {
        id: randomUUID(),
        author: { role: "user" },
        content: { content_type: "text", parts: [message] },
      },
    ],
    model: {
      // "auto" picks the user's default model in the web client (GPT-5 / GPT-4o etc).
      default: {},
    },
    parent_message_id: randomUUID(),
    timezone_offset_min: new Date().getTimezoneOffset(),
    suggestions: [],
    history_and_training_disabled: false,
    conversation_mode: { kind: "primary_assistant" },
    force_paragen: false,
    force_paragen_model_slug: "",
    force_use_sse: true,
    force_rate_limit: false,
    reset_rate_limits: false,
    websocket_request_id: randomUUID(),
    conversation_origin: null,
    client_contextual_info: {
      is_dark_mode: false,
      time_since_loaded: Math.floor(Math.random() * 5000 + 1000),
      page_height: 900,
      page_width: 1440,
      pixel_ratio: 1,
      screen_height: 1080,
      screen_width: 1920,
    },
    Parsons_version: 0,
  };
}

/**
 * Parse one SSE buffer chunk into [events, remainder]. Handles partial lines.
 * Each event is the parsed JSON object from a `data: {...}` line, or the
 * sentinel string "[DONE]".
 */
function parseSseChunk(buf, leftover) {
  const data = leftover + buf;
  const lines = data.split("\n");
  const events = [];
  // Keep the last (possibly partial) line for next time.
  const nextLeftover = lines.pop() ?? "";

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || !line.startsWith("data:")) continue;
    const payload = line.slice(5).trim();
    if (payload === "[DONE]") {
      events.push("[DONE]");
      continue;
    }
    try {
      events.push(JSON.parse(payload));
    } catch {
      // ignore malformed/non-JSON keepalive lines
    }
  }
  return [events, nextLeftover];
}

/**
 * Extract the incremental text delta from a parsed backend-api event object.
 * Backend sends `message.content.parts` arrays that grow over time; we emit the
 * FULL current text and let the caller diff (simplest + robust to reordering).
 */
function eventText(evt) {
  const parts = evt?.message?.content?.parts;
  if (!Array.isArray(parts)) return null;
  return parts.map((p) => (typeof p === "string" ? p : "")).join("");
}

/**
 * Send a message via the direct backend and return the full assistant reply.
 * If opts.onToken is provided, it is called with incremental deltas as they
 * stream in (true SSE token streaming).
 * @param {string} message
 * @param {{onToken?: (delta: string) => void}} [opts]
 * @returns {Promise<string>}
 */
export async function chatAPI(message, opts = {}) {
  const { onToken } = opts;
  return withSessionScope(async ({ page }) => {
    // The access token call needs to go through the browser's request context so
    // it carries the saved cookies + correct headers/CF tokens.
    const accessToken = await getAccessToken(page);

    const body = buildPayload(message);
    let fullText = "";
    let lastEmit = "";

    const resp = await page.request.post(`${BASE}/backend-api/f/conversation`, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
        Accept: "text/event-stream",
      },
      data: body,
      timeout: 90_000,
    });

    if (!resp.ok()) {
      const status = resp.status();
      const body = (await resp.text().catch(() => "")).slice(0, 64 * 1024);
      const limit = rateLimitResponseInfo({
        status,
        headers: resp.headers(),
        body,
      });
      if (limit) {
        const err = new Error(limit.message);
        err.rateLimited = true;
        err.backoffMs = limit.backoffMs;
        err.rateLimitSource = limit.source;
        err.chatgptResponseStatus = status;
        throw err;
      }
      const sample = body.slice(0, 200);
      // 403/422 here is EXPECTED without the sentinel proof/turnstile tokens,
      // which only the real web client JS can produce. Let the caller fall back
      // to the playwright backend.
      throw new Error(
        `api-backend: /backend-api/f/conversation returned ${status} — ${sample}. ` +
          `(Expected without sentinel tokens; falling back to UI backend.)`
      );
    }

    // Consume the SSE stream.
    const stream = await resp.body(); // Buffer
    let leftover = "";
    let events;
    [events, leftover] = parseSseChunk(stream.toString("utf8"), leftover);

    for (const evt of events) {
      if (evt === "[DONE]") break;
      const text = eventText(evt);
      if (text != null && text.length > lastEmit.length && text.startsWith(lastEmit)) {
        if (onToken) onToken(text.slice(lastEmit.length));
        lastEmit = text;
        fullText = text;
      } else if (text != null) {
        // Fallback: text changed in a non-prefix way — just track the latest.
        fullText = text;
      }
    }

    if (!fullText) {
      throw new Error("api-backend: stream produced no content (auth/payload may have changed)");
    }
    return fullText.trim();
  });
}
