import type { TLRecord, TLShape } from "tldraw";
import { InkShapeProps, inkStrokeWidth, renderInk } from "./ink-rendering";

const FORMAT_HEADER = "% overleaf-whiteboard-format: 1";
const RECORD_PREFIX = "% overleaf-whiteboard-record: ";
const PIXELS_PER_CENTIMETER = 96 / 2.54;
const BASE64_ALPHABET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

export type TikzImportItem =
  | {
      type: "geo";
      geo: "rectangle" | "ellipse";
      x: number;
      y: number;
      w: number;
      h: number;
    }
  | {
      type: "arrow";
      x1: number;
      y1: number;
      x2: number;
      y2: number;
    }
  | { type: "text" | "latex"; x: number; y: number; value: string }
  | {
      type: "plot";
      expression: string;
      xMin: number;
      xMax: number;
      yMin: number;
      yMax: number;
    }
  | { type: "source-fragment"; source: string; warning: string };

export type TikzImportResult =
  | { kind: "round-trip"; records: TLRecord[]; warnings: string[] }
  | { kind: "parsed"; items: TikzImportItem[]; warnings: string[] };

export function exportWhiteboardToTikz({
  boardId,
  records,
}: {
  boardId: string;
  records: TLRecord[];
}) {
  const shapes = records.filter(isShapeRecord);
  const lines = [
    FORMAT_HEADER,
    `% overleaf-whiteboard-board: ${sanitizeComment(boardId)}`,
    "% Generated by Overleaf Whiteboard. Edit through explicit import/export.",
    "\\begin{tikzpicture}[x=1cm,y=1cm]",
  ];

  for (const shape of shapes) {
    lines.push(`${RECORD_PREFIX}${encodeRecord(shape)}`);
    lines.push(...shapeToTikz(shape));
  }

  lines.push("\\end{tikzpicture}", "");
  return lines.join("\n");
}

function isShapeRecord(record: TLRecord): record is TLShape {
  return record.typeName === "shape";
}

export function importWhiteboardFromTikz(source: string): TikzImportResult {
  if (source.includes(FORMAT_HEADER)) {
    const records: TLRecord[] = [];
    const warnings: string[] = [];
    for (const line of source.split("\n")) {
      if (!line.startsWith(RECORD_PREFIX)) continue;
      try {
        records.push(decodeRecord(line.slice(RECORD_PREFIX.length)));
      } catch {
        warnings.push("A generated whiteboard record could not be decoded.");
      }
    }
    if (records.length > 0) return { kind: "round-trip", records, warnings };
    warnings.push(
      "The generated TikZ file contained no recoverable whiteboard records.",
    );
    return {
      kind: "parsed",
      items: parseCommonTikz(source, warnings),
      warnings,
    };
  }

  const warnings: string[] = [];
  return { kind: "parsed", items: parseCommonTikz(source, warnings), warnings };
}

function shapeToTikz(shape: TLShape): string[] {
  const preservedSource = (shape.meta as Record<string, unknown>)
    .tikzSourceFragment;
  if (typeof preservedSource === "string") {
    return preservedSource.split("\n");
  }
  const props = shape.props as Record<string, unknown>;
  const x = toTikz(shape.x);
  const y = toTikz(-shape.y);
  const id = sanitizeComment(shape.id);

  if (shape.type === "geo") {
    const width = numberProp(props.w, 100);
    const height = numberProp(props.h, 100);
    const geo = String(props.geo ?? "rectangle");
    if (geo === "ellipse") {
      return [
        `\\draw ${point(shape.x + width / 2, shape.y + height / 2)} ellipse [x radius=${toTikz(width / 2)}, y radius=${toTikz(height / 2)}]; % ${id}`,
      ];
    }
    if (geo === "triangle") {
      return [
        `\\draw ${point(shape.x + width / 2, shape.y)} -- ${point(shape.x + width, shape.y + height)} -- ${point(shape.x, shape.y + height)} -- cycle; % ${id}`,
      ];
    }
    if (geo === "diamond") {
      return [
        `\\draw ${point(shape.x + width / 2, shape.y)} -- ${point(shape.x + width, shape.y + height / 2)} -- ${point(shape.x + width / 2, shape.y + height)} -- ${point(shape.x, shape.y + height / 2)} -- cycle; % ${id}`,
      ];
    }
    return [
      `\\draw (${x},${y}) rectangle ++(${toTikz(width)},${toTikz(-height)}); % ${id}`,
    ];
  }

  if (shape.type === "arrow") {
    const start = pointFromUnknown(props.start);
    const end = pointFromUnknown(props.end);
    return [
      `\\draw[->] ${point(shape.x + start.x, shape.y + start.y)} -- ${point(shape.x + end.x, shape.y + end.y)}; % ${id}`,
    ];
  }

  if (shape.type === "text") {
    return [
      `\\node[anchor=north west] at (${x},${y}) {${escapeTexText(richTextToPlainText(props.richText))}}; % ${id}`,
    ];
  }

  if (shape.type === "latex") {
    return [
      `\\node[anchor=north west] at (${x},${y}) {$${String(props.latex ?? "")}$}; % ${id}`,
    ];
  }

  if (shape.type === "plot") {
    const expression = sanitizePlotExpression(String(props.expression ?? "x"));
    return [
      `\\begin{axis}[at={(${x}cm,${y}cm)},anchor=north west,width=${toTikz(numberProp(props.w, 360))}cm,height=${toTikz(numberProp(props.h, 240))}cm,xmin=${numberProp(props.xMin, -10)},xmax=${numberProp(props.xMax, 10)},ymin=${numberProp(props.yMin, -2)},ymax=${numberProp(props.yMax, 2)},grid=both]`,
      `  \\addplot[domain=${numberProp(props.xMin, -10)}:${numberProp(props.xMax, 10)},samples=320] {${expression}}; % ${id}`,
      "\\end{axis}",
    ];
  }

  if (shape.type === "ink") {
    const inkProps = props as InkShapeProps;
    const rendered = renderInk(inkProps, shape.id);
    if (!rendered.error) {
      return [
        ...rendered.strokes.flatMap((stroke) =>
          stroke.polylines
            .filter((polyline) => polyline.length > 1)
            .map(
              (polyline) =>
                `\\draw[${inkTikzOptions(inkProps, stroke.width, stroke.opacity)}] plot[smooth] coordinates {${polyline
                  .map((value) => point(shape.x + value.x, shape.y + value.y))
                  .join(" ")}}; % ${id}`,
            ),
        ),
        ...rendered.decorations.map(
          (decoration) =>
            `\\draw[${inkTikzOptions(inkProps, decoration.width, decoration.opacity)}] ${decoration.polyline
              .map((value) => point(shape.x + value.x, shape.y + value.y))
              .join(" -- ")}; % ${id}`,
        ),
      ];
    }
  }

  if (shape.type === "draw") {
    return drawPolylines(props.segments)
      .filter((polyline) => polyline.length > 1)
      .map(
        (polyline) =>
          `\\draw plot[smooth] coordinates {${polyline
            .map((value) => point(shape.x + value.x, shape.y + value.y))
            .join(" ")}}; % ${id}`,
      );
  }

  return [
    `% Unsupported visual shape ${id}; round-trip metadata above preserves it.`,
  ];
}

function parseCommonTikz(source: string, warnings: string[]) {
  const items: TikzImportItem[] = [];
  const consumed = new Set<string>();

  const consume = (match: RegExpMatchArray, item: TikzImportItem) => {
    items.push(item);
    consumed.add(match[0]);
  };

  for (const match of source.matchAll(
    /\\draw(?:\[[^\]]*\])?\s*\((-?[\d.]+),\s*(-?[\d.]+)\)\s*rectangle\s*(\+\+)?\((-?[\d.]+),\s*(-?[\d.]+)\)\s*;/g,
  )) {
    const x1 = fromTikz(Number(match[1]));
    const y1 = -fromTikz(Number(match[2]));
    const relative = Boolean(match[3]);
    const x2 = relative
      ? x1 + fromTikz(Number(match[4]))
      : fromTikz(Number(match[4]));
    const y2 = relative
      ? y1 - fromTikz(Number(match[5]))
      : -fromTikz(Number(match[5]));
    consume(match, {
      type: "geo",
      geo: "rectangle",
      x: Math.min(x1, x2),
      y: Math.min(y1, y2),
      w: Math.abs(x2 - x1),
      h: Math.abs(y2 - y1),
    });
  }

  for (const match of source.matchAll(
    /\\draw(?:\[[^\]]*\])?\s*\((-?[\d.]+),\s*(-?[\d.]+)\)\s*--\s*\((-?[\d.]+),\s*(-?[\d.]+)\)\s*;/g,
  )) {
    consume(match, {
      type: "arrow",
      x1: fromTikz(Number(match[1])),
      y1: -fromTikz(Number(match[2])),
      x2: fromTikz(Number(match[3])),
      y2: -fromTikz(Number(match[4])),
    });
  }

  for (const match of source.matchAll(
    /\\node(?:\[[^\]]*\])?\s*at\s*\((-?[\d.]+),\s*(-?[\d.]+)\)\s*\{([^{}]*)\}\s*;/g,
  )) {
    const raw = match[3].trim();
    const isLatex = raw.startsWith("$") && raw.endsWith("$");
    consume(match, {
      type: isLatex ? "latex" : "text",
      x: fromTikz(Number(match[1])),
      y: -fromTikz(Number(match[2])),
      value: isLatex ? raw.slice(1, -1) : raw,
    });
  }

  for (const match of source.matchAll(
    /\\addplot(?:\[([^\]]*)\])?\s*\{([^{}]+)\}\s*;/g,
  )) {
    const domain = match[1]?.match(/domain\s*=\s*(-?[\d.]+)\s*:\s*(-?[\d.]+)/);
    consume(match, {
      type: "plot",
      expression: match[2].trim(),
      xMin: domain ? Number(domain[1]) : -10,
      xMax: domain ? Number(domain[2]) : 10,
      yMin: -10,
      yMax: 10,
    });
  }

  const commands = source
    .split("\n")
    .map((line) => line.trim())
    .filter(
      (line) =>
        line.startsWith("\\") &&
        !line.startsWith("\\begin{tikzpicture}") &&
        !line.startsWith("\\end{tikzpicture}") &&
        !line.startsWith("\\begin{axis}") &&
        !line.startsWith("\\end{axis}") &&
        ![...consumed].some((value) => value.includes(line)),
    );

  if (commands.length > 0) {
    warnings.push(
      `${commands.length} unsupported TikZ command(s) were preserved as source.`,
    );
    items.push({
      type: "source-fragment",
      source: commands.join("\n"),
      warning: "Unsupported TikZ preserved for manual editing",
    });
  }

  return items;
}

function encodeRecord(record: TLRecord) {
  const bytes = new TextEncoder().encode(JSON.stringify(record));
  let output = "";
  for (let index = 0; index < bytes.length; index += 3) {
    const first = bytes[index];
    const second = bytes[index + 1];
    const third = bytes[index + 2];
    const value = (first << 16) | ((second ?? 0) << 8) | (third ?? 0);
    output += BASE64_ALPHABET[(value >> 18) & 63];
    output += BASE64_ALPHABET[(value >> 12) & 63];
    output += second === undefined ? "=" : BASE64_ALPHABET[(value >> 6) & 63];
    output += third === undefined ? "=" : BASE64_ALPHABET[value & 63];
  }
  return output;
}

function decodeRecord(value: string): TLRecord {
  const encoded = value.trim();
  if (encoded.length % 4 !== 0 || !/^[a-zA-Z0-9+/]*={0,2}$/.test(encoded)) {
    throw new Error("Invalid generated whiteboard record");
  }
  const bytes: number[] = [];
  for (let index = 0; index < encoded.length; index += 4) {
    const characters = encoded.slice(index, index + 4);
    const value = characters
      .split("")
      .reduce(
        (result, character) =>
          (result << 6) |
          (character === "=" ? 0 : BASE64_ALPHABET.indexOf(character)),
        0,
      );
    bytes.push((value >> 16) & 255);
    if (characters[2] !== "=") bytes.push((value >> 8) & 255);
    if (characters[3] !== "=") bytes.push(value & 255);
  }
  return JSON.parse(
    new TextDecoder().decode(Uint8Array.from(bytes)),
  ) as TLRecord;
}

function point(x: number, y: number) {
  return `(${toTikz(x)},${toTikz(-y)})`;
}

function toTikz(value: number) {
  return round(value / PIXELS_PER_CENTIMETER);
}

function fromTikz(value: number) {
  return value * PIXELS_PER_CENTIMETER;
}

function round(value: number) {
  return Math.round(value * 10000) / 10000;
}

function numberProp(value: unknown, fallback: number) {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function pointFromUnknown(value: unknown) {
  if (!value || typeof value !== "object") return { x: 0, y: 0 };
  const point = value as { x?: unknown; y?: unknown };
  return { x: numberProp(point.x, 0), y: numberProp(point.y, 0) };
}

function drawPolylines(value: unknown) {
  if (!Array.isArray(value)) return [];
  return value.map((segment) => {
    if (!segment || typeof segment !== "object") return [];
    const points = (segment as { points?: unknown }).points;
    if (!Array.isArray(points)) return [];
    return points.map(pointFromUnknown);
  });
}

function inkTikzOptions(
  props: InkShapeProps,
  width = inkStrokeWidth(props.size),
  opacity = 1,
) {
  const color = /^#[\da-f]{6}$/i.test(props.color)
    ? props.color.slice(1)
    : "1F2937";
  const red = Number.parseInt(color.slice(0, 2), 16);
  const green = Number.parseInt(color.slice(2, 4), 16);
  const blue = Number.parseInt(color.slice(4, 6), 16);
  return [
    `line width=${round(width)}pt`,
    "line cap=round",
    "line join=round",
    ...(opacity < 1 ? [`opacity=${round(opacity)}`] : []),
    `draw={rgb,255:red,${red};green,${green};blue,${blue}}`,
  ].join(",");
}

function richTextToPlainText(value: unknown): string {
  if (!value || typeof value !== "object") return "";
  const record = value as { text?: unknown; content?: unknown };
  if (typeof record.text === "string") return record.text;
  if (Array.isArray(record.content)) {
    return record.content.map(richTextToPlainText).join("");
  }
  return "";
}

function escapeTexText(value: string) {
  return value
    .replace(/([#$%&_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}");
}

function sanitizePlotExpression(value: string) {
  return value.replace(/[^a-zA-Z0-9_+\-*/^()., ]/g, "");
}

function sanitizeComment(value: string) {
  return value.replace(/[\r\n%]/g, " ");
}
